module.exports = {
  EVENT_MESSAGE: 'EVENT_MESSAGE',
  EVENT_DISCONNECTED: 'EVENT_DISCONNECTED',

  EVENT_AUDIO_PLAY: 'EVENT_AUDIO_PLAY',
  EVENT_AUDIO_PAUSE: 'EVENT_AUDIO_PAUSE',
  EVENT_AUDIO_SEEK: 'EVENT_AUDIO_SEEK',
  EVENT_AUDIO_STEP_FORWARDS: 'EVENT_AUDIO_STEP_FORWARDS',
  EVENT_AUDIO_STEP_BACKWARDS: 'EVENT_AUDIO_STEP_BACKWARDS',
  EVENT_AUDIO_VOLUME: 'EVENT_AUDIO_VOLUME',
  EVENT_AUDIO_MUTE: 'EVENT_AUDIO_MUTE',
  EVENT_AUDIO_UNMUTE: 'EVENT_AUDIO_UNMUTE',

  EVENT_VIDEO_PLAY: 'EVENT_VIDEO_PLAY',
  EVENT_VIDEO_PAUSE: 'EVENT_VIDEO_PAUSE',
  EVENT_VIDEO_SEEK: 'EVENT_VIDEO_SEEK',
  EVENT_VIDEO_SEEKING: 'EVENT_VIDEO_SEEKING',
  EVENT_VIDEO_SEEKED: 'EVENT_VIDEO_SEEKED',
  EVENT_VIDEO_STEP_FORWARDS: 'EVENT_VIDEO_STEP_FORWARDS',
  EVENT_VIDEO_STEP_BACKWARDS: 'EVENT_VIDEO_STEP_BACKWARDS',
  EVENT_VIDEO_VOLUME: 'EVENT_VIDEO_VOLUME',
  EVENT_VIDEO_MUTE: 'EVENT_VIDEO_MUTE',
  EVENT_VIDEO_UNMUTE: 'EVENT_VIDEO_UNMUTE'
};
