module.exports = {
  EVENT_MESSAGE: 'EVENT_MESSAGE',

  EVENT_AUDIO_PLAY: 'EVENT_AUDIO_PLAY',
  EVENT_AUDIO_PAUSE: 'EVENT_AUDIO_PAUSE',
  EVENT_AUDIO_STOP: 'EVENT_AUDIO_STOP',
  EVENT_AUDIO_SEEK: 'EVENT_AUDIO_SEEK',
  EVENT_AUDIO_STEP_FORWARDS: 'EVENT_AUDIO_STEP_FORWARDS',
  EVENT_AUDIO_STEP_BACKWARDS: 'EVENT_AUDIO_STEP_BACKWARDS',
  EVENT_AUDIO_VOLUME: 'EVENT_AUDIO_VOLUME',
  EVENT_AUDIO_MUTE: 'EVENT_AUDIO_MUTE',
  EVENT_AUDIO_UNMUTE: 'EVENT_AUDIO_UNMUTE',
};
